name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- master
- dotliquid
- refs/heads/dotliquid
pr:
- dotliquid
- main
- templates/*

variables:
  solution: '**/*.sln'
  unitTestProjects: "**/*UnitTests/*.csproj"
  publishProject: "**/*Tool/*.csproj"
  functionalTests: "**/*FunctionalTests/*.csproj"
  buildConfiguration: 'Release'
  major: 5
  minor: 0
  patch: 1
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: FunctionalTests
  jobs:
  - job: OSX_Functional_Test
    pool:
        vmImage: 'macOS-10.15'
    continueOnError: false
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable
    - script: |
        docker login
        docker run --rm -d -p 5000:5000 --name registryOSX registry:2
      displayName: start registryOSX
    - script: |
        chmod +x FhirConverterBuild/**/**/oras*
        dotnet test FhirConverterBuild/**/*FunctionalTests.dll
      displayName: Functional Tests
    - task: Docker@2
      displayName: stop registryOSX
      condition: succeededOrFailed()
      inputs:
        command: stop
        container: registryOSX
    
    #need delete files for self-hosted agent
    - task: DeleteFiles@1
      inputs:
        Contents: '**/*' 

- stage: Release
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: publish
    pool:
        vmImage: 'windows-2019'
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifacts'
      inputs:
        artifactName: FhirConverterBuild
        downloadPath: $(System.DefaultWorkingDirectory)

    - task: GithubRelease@0 
      displayName: 'Create GitHub Release'      
      inputs:
        gitHubConnection: githubpipeline
        repositoryName: microsoft/FHIR-Converter
        isDraft: true
        tagSource: manual
        tag: v$(major).$(minor).$(patch)      
        assets: |
          $(System.DefaultWorkingDirectory)/FhirConverterBuild/bin/**
          $(System.DefaultWorkingDirectory)/FhirConverterBuild/data/Templates/Hl7v2DefaultTemplates.tar.gz
          $(System.DefaultWorkingDirectory)/FhirConverterBuild/data/Templates/CcdaDefaultTemplates.tar.gz
          $(System.DefaultWorkingDirectory)/FhirConverterBuild/data/Templates/JsonDefaultTemplates.tar.gz
          $(System.DefaultWorkingDirectory)/FhirConverterBuild/data/Templates/Stu3ToR4DefaultTemplates.tar.gz
